apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-deploy
  labels:
    app: htt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htt
  template:
    metadata:
      labels:
        app: htt
    spec:
      containers:
      - name: httpbin
        image: uditanshu/newimage
        ports:
        - containerPort: 8000
          name: guicorn

---
apiVersion: apps/v1
kind: Service
metadata:
  name: httpbin-deploy
  labels:
    app: htt
spec:
  type: NodePort
  selector:
    app: htt
  ports:
    - port: 8000
      targetPort: 8000
